# Generated by Django 5.0.7 on 2024-07-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_trigger_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('deleted', 'Deleted'), ('triggered', 'Triggered')], default='created', max_length=10),
        ),
    ]
