# Generated by Django 5.0.7 on 2024-07-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_trigger_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BTCPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
