# Generated by Django 5.0.7 on 2024-07-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_btcprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='comparison',
            field=models.CharField(default='NA'),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('deleted', 'Deleted'), ('triggered', 'Triggered')], default='created'),
        ),
    ]
