
services:
  rabbitmq:
    image: rabbitmq:3-management
    healthcheck:
      test: ["CMD-SHELL", "rabbitmqctl status"]
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Management UI port

  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: abc@abc.com
      PGADMIN_DEFAULT_PASSWORD: abc
    ports:
      - "8080:80"
    depends_on:
      - db

  redis:
    image: redis:alpine

    ports:
      - "6379:6379"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - rabbitmq

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    command: celery -A alerter worker --loglevel=info --concurrency=1 #further testing required to see if only one celery worker is enough
    volumes:
      - .:/app
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - redis
      - rabbitmq
      - web

volumes:
  postgres_data:
