# Use the official Python image.
FROM python:3.10-slim

# Set environment variables.
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory.
WORKDIR /app

# Install dependencies.
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copy the project files.
COPY . /app/

# Start the Celery worker.
CMD ["celery", "-A", "alerter", "worker", "--loglevel=info"]
